POST http://localhost:8888/online-order-device/register
Content-Type: application/x-www-form-urlencoded

pairingCode=UqMciz&name=Sunmi&appName=Pos-Germany.apk&appVersion=1.51&type=webShopTerminal

###
